<?php

return [
    "Accounting", 
    "Art", 
    "Agriculture", 
    "Beauty", 
    "Construction", 
    "Consulting", 
    "Copywriting", 
    "Creative", 
    "Creator", 
    "Design", 
    "Education", 
    "Entertainment", 
    "Environment", 
    "Fashion", 
    "Finance", 
    "Fitness", 
    "Food & Drink", 
    "Gaming", 
    "Government", 
    "Healthcare", 
    "Home & Maintenance", 
    "Hospitality", 
    "Insurance", 
    "Legal", 
    "Music", 
    "Non-profit", 
    "Personal", 
    "Pets", 
    "Photography", 
    "Real Estate", 
    "Recruiting", 
    "Restaurants", 
    "Retail", 
    "Software", 
    "Sports", 
    "Technology", 
    "Travel", 
    "Wedding", 
    "Telecommunications"
];