<?php

return [
    "email" => [
        "name" => "Email",
        "address" => "mailto: %s",
        "icon" => "iconfont icon-Email",
        "placeholder" => "Your email",
    ],
    "instagram" => [
        "name" => "Instagram",
        "address" => "https://instagram.com/%s",
        "icon" => "iconfont icon-Instagram",
        "placeholder" => "Your username",
    ],
    "whatsapp" => [
        "name" => "Whatsapp",
        "address" => "https://api.whatsapp.com/send?phone=%s",
        "icon" => "iconfont icon-Whatsapp",
        "placeholder" => "Phone plus country code: ex: +91123123121",
    ],
    "tiktok" => [
        "name" => "TikTok",
        "address" => "https://tiktok.com/@%s",
        "icon" => "iconfont icon-TikTok",
        "placeholder" => "Your username",
    ],
    "twitter" => [
        "name" => "X",
        "address" => "https://twitter.com/%s",
        "icon" => "iconfont icon-Twitter",
        "placeholder" => "Your username",
    ],
    "facebook" => [
        "name" => "Facebook",
        "address" => "%s",
        "icon" => "iconfont icon-Facebook",
        "placeholder" => "Your facebook page link",
    ],
    "youtube" => [
        "name" => "YouTube",
        "address" => "https://youtube.com/@%s",
        "icon" => "iconfont icon-YouTube",
        "placeholder" => "Your youtube username",
    ],
    "phone" => [
        "name" => "Phone",
        "address" => "tel:%s",
        "icon" => "iconfont icon-Phone",
        "placeholder" => "Your link",
    ],
    "spotify" => [
        "name" => "Spotify",
        "address" => "%s",
        "icon" => "iconfont icon-Spotify",
        "placeholder" => "Your link",
    ],
    "website" => [
        "name" => "Website",
        "address" => "%s",
        "icon" => "iconfont icon-Website",
        "placeholder" => "Your link",
    ],
    "linkedin" => [
        "name" => "LinkedIn",
        "address" => "%s",
        "icon" => "iconfont icon-LinkedIn",
        "placeholder" => "Your link",
    ],
    "twitch" => [
        "name" => "Twitch",
        "address" => "https://twitch.tv/%s",
        "icon" => "iconfont icon-Twitch",
        "placeholder" => "Your username",
    ],
    "discord" => [
        "name" => "Discord",
        "address" => "%s",
        "icon" => "iconfont icon-Discord",
        "placeholder" => "Your link",
    ],
    "telegram" => [
        "name" => "Telegram",
        "address" => "%s",
        "icon" => "iconfont icon-telegram",
        "placeholder" => "Your link",
    ],
    "snapchat" => [
        "name" => "Snapchat",
        "address" => "%s",
        "icon" => "iconfont icon-Snapchat",
        "placeholder" => "Your link",
    ],
    "shopee" => [
        "name" => "Shopee",
        "address" => "%s",
        "icon" => "iconfont icon-shopee",
        "placeholder" => "Your link",
    ],
    "pinterest" => [
        "name" => "Pinterest",
        "address" => "%s",
        "icon" => "iconfont icon-Pinterest",
        "placeholder" => "Your link",
    ],
    "youtubemusic" => [
        "name" => "Youtubemusic",
        "address" => "%s",
        "icon" => "iconfont icon-a-youtubemusic",
        "placeholder" => "Your link",
    ],
    "genericshop" => [
        "name" => "GenericShop",
        "address" => "%s",
        "icon" => "iconfont icon-a-GenericShop",
        "placeholder" => "Your link",
    ],
    "soundcloud" => [
        "name" => "Soundcloud",
        "address" => "%s",
        "icon" => "iconfont icon-a-soundcloud",
        "placeholder" => "Your link",
    ],
    "fbmessenger" => [
        "name" => "FBMessenger",
        "address" => "%s",
        "icon" => "iconfont icon-a-FBMessenger",
        "placeholder" => "Your link",
    ],
    "applemusic" => [
        "name" => "Applemusic",
        "address" => "%s",
        "icon" => "iconfont icon-a-applemusic",
        "placeholder" => "Your link",
    ],
    "paypal" => [
        "name" => "Paypal",
        "address" => "%s",
        "icon" => "iconfont icon-paypal",
        "placeholder" => "Your link",
    ],
    "line" => [
        "name" => "Line",
        "address" => "%s",
        "icon" => "iconfont icon-line",
        "placeholder" => "Your link",
    ],
    "newmusicslives" => [
        "name" => "NewMusicsLives",
        "address" => "%s",
        "icon" => "iconfont icon-a-NewMusicsLives",
        "placeholder" => "Your link",
    ],
    "amazon" => [
        "name" => "Amazon",
        "address" => "%s",
        "icon" => "iconfont icon-amazon",
        "placeholder" => "Your link",
    ],
    "deezer" => [
        "name" => "Deezer",
        "address" => "%s",
        "icon" => "iconfont icon-deezer",
        "placeholder" => "Your link",
    ],
    "behance" => [
        "name" => "Behance",
        "address" => "%s",
        "icon" => "iconfont icon-behance",
        "placeholder" => "Your link",
    ],
    "tumblr" => [
        "name" => "Tumblr",
        "address" => "%s",
        "icon" => "iconfont icon-Tumblr",
        "placeholder" => "Your link",
    ],
    "steam" => [
        "name" => "Steam",
        "address" => "%s",
        "icon" => "iconfont icon-steam",
        "placeholder" => "Your link",
    ],
    "onlyfans1" => [
        "name" => "Onlyfans",
        "address" => "%s",
        "icon" => "iconfont icon-onlyfans1",
        "placeholder" => "Your link",
    ],
    "googledrive" => [
        "name" => "Googledrive",
        "address" => "%s",
        "icon" => "iconfont icon-a-googledrive",
        "placeholder" => "Your link",
    ],
    "wattpad" => [
        "name" => "Wattpad",
        "address" => "%s",
        "icon" => "iconfont icon-wattpad",
        "placeholder" => "Your link",
    ],
    "etsy" => [
        "name" => "Etsy",
        "address" => "%s",
        "icon" => "iconfont icon-Etsy",
        "placeholder" => "Your link",
    ],
    "shopify" => [
        "name" => "Shopify",
        "address" => "%s",
        "icon" => "iconfont icon-shopify",
        "placeholder" => "Your link",
    ],
    "reddit" => [
        "name" => "Reddit",
        "address" => "%s",
        "icon" => "iconfont icon-Reddit",
        "placeholder" => "Your link",
    ],
    "viber" => [
        "name" => "Viber",
        "address" => "%s",
        "icon" => "iconfont icon-Viber",
        "placeholder" => "Your link",
    ],
    "goodreads" => [
        "name" => "Goodreads",
        "address" => "%s",
        "icon" => "iconfont icon-goodreads",
        "placeholder" => "Your link",
    ],
    "skype" => [
        "name" => "Skype",
        "address" => "%s",
        "icon" => "iconfont icon-Skype",
        "placeholder" => "Your link",
    ],
    "medium" => [
        "name" => "Medium",
        "address" => "%s",
        "icon" => "iconfont icon-Medium",
        "placeholder" => "Your link",
    ],
    "googleplay" => [
        "name" => "Googleplay",
        "address" => "%s",
        "icon" => "iconfont icon-googleplay",
        "placeholder" => "Your link",
    ],
    "vimeo" => [
        "name" => "Vimeo",
        "address" => "%s",
        "icon" => "iconfont icon-vimeo",
        "placeholder" => "Your link",
    ],
    "patreon" => [
        "name" => "Patreon",
        "address" => "%s",
        "icon" => "iconfont icon-patreon",
        "placeholder" => "Your link",
    ],
    "bandcamp" => [
        "name" => "Bandcamp",
        "address" => "%s",
        "icon" => "iconfont icon-bandcamp",
        "placeholder" => "Your link",
    ],
    "vsco" => [
        "name" => "VSCO",
        "address" => "%s",
        "icon" => "iconfont icon-VSCO",
        "placeholder" => "Your link",
    ],
    "vk" => [
        "name" => "VK",
        "address" => "%s",
        "icon" => "iconfont icon-VK",
        "placeholder" => "Your link",
    ],
    "applepodcast" => [
        "name" => "ApplePodcast",
        "address" => "%s",
        "icon" => "iconfont icon-a-ApplePodcast",
        "placeholder" => "Your link",
    ],
    "wechat" => [
        "name" => "Wechat",
        "address" => "%s",
        "icon" => "iconfont icon-wechat",
        "placeholder" => "Your link",
    ],
    "mixcloud" => [
        "name" => "Mixcloud",
        "address" => "%s",
        "icon" => "iconfont icon-mixcloud",
        "placeholder" => "Your link",
    ],
    "appstore" => [
        "name" => "Apple store",
        "address" => "%s",
        "icon" => "iconfont icon-a-appstore",
        "placeholder" => "Your link",
    ],
    "napster" => [
        "name" => "Napster",
        "address" => "%s",
        "icon" => "iconfont icon-napster",
        "placeholder" => "Your link",
    ],
    "tripadvisor" => [
        "name" => "Trip advisor",
        "address" => "%s",
        "icon" => "la la-tripadvisor",
        "placeholder" => "Your link",
    ],
    "flickr" => [
        "name" => "Flickr",
        "address" => "%s",
        "icon" => "iconfont icon-flickr",
        "placeholder" => "Your link",
    ],
    "ebay" => [
        "name" => "Ebay",
        "address" => "%s",
        "icon" => "iconfont icon-ebay",
        "placeholder" => "Your link",
    ],
    "clubhouse" => [
        "name" => "Clubhouse",
        "address" => "%s",
        "icon" => "iconfont icon-Clubhouse",
        "placeholder" => "Your link",
    ],
    "flipboard" => [
        "name" => "Flipboard",
        "address" => "%s",
        "icon" => "iconfont icon-flipboard",
        "placeholder" => "Your link",
    ],
    "lastfm" => [
        "name" => "LastFM",
        "address" => "%s",
        "icon" => "iconfont icon-a-LastFM",
        "placeholder" => "Your link",
    ],
    "weibo" => [
        "name" => "Weibo",
        "address" => "%s",
        "icon" => "iconfont icon-Weibo",
        "placeholder" => "Your link",
    ],
    "fansly" => [
        "name" => "Fansly",
        "address" => "%s",
        "icon" => "iconfont icon-Fansly",
        "placeholder" => "Your link",
    ],
    "digg" => [
        "name" => "Digg",
        "address" => "%s",
        "icon" => "iconfont icon-digg",
        "placeholder" => "Your link",
    ],
    "buymeacoffee" => [
        "name" => "Buymeacoffee",
        "address" => "%s",
        "icon" => "iconfont icon-Buymeacoffee",
        "placeholder" => "Your link",
    ],
    "vibepay" => [
        "name" => "VibePay",
        "address" => "%s",
        "icon" => "iconfont icon-VibePay",
        "placeholder" => "Your link",
    ],
    "venmo" => [
        "name" => "Venmo",
        "address" => "%s",
        "icon" => "iconfont icon-venmo",
        "placeholder" => "Your link",
    ],
    "zelle" => [
        "name" => "Zelle",
        "address" => "%s",
        "icon" => "iconfont icon-Zelle",
        "placeholder" => "Your link",
    ],
    "letterboxd" => [
        "name" => "Letterboxd",
        "address" => "%s",
        "icon" => "iconfont icon-Letterboxd",
        "placeholder" => "Your link",
    ],
    "googleblog" => [
        "name" => "Googleblog",
        "address" => "%s",
        "icon" => "iconfont icon-a-Googleblog",
        "placeholder" => "Your link",
    ],
    "vinted" => [
        "name" => "Vinted",
        "address" => "%s",
        "icon" => "iconfont icon-Vinted",
        "placeholder" => "Your link",
    ],
    "square" => [
        "name" => "Square",
        "address" => "%s",
        "icon" => "iconfont icon-square",
        "placeholder" => "Your link",
    ],
    "artstation" => [
        "name" => "Artstation",
        "address" => "%s",
        "icon" => "iconfont icon-artstation",
        "placeholder" => "Your link",
    ],
    "gmazonmusic" => [
        "name" => "Gmazonmusic",
        "address" => "%s",
        "icon" => "iconfont icon-Gmazonmusic",
        "placeholder" => "Your link",
    ],
    "googlemaps" => [
        "name" => "Googlemaps",
        "address" => "%s",
        "icon" => "iconfont icon-Googlemaps",
        "placeholder" => "Your link",
    ],
    "waze" => [
        "name" => "Waze",
        "address" => "%s",
        "icon" => "iconfont icon-waze",
        "placeholder" => "Your link",
    ],
    "uber" => [
        "name" => "Uber",
        "address" => "%s",
        "icon" => "iconfont icon-Uber",
        "placeholder" => "Your link",
    ],
    "tokopedia1" => [
        "name" => "Tokopedia",
        "address" => "%s",
        "icon" => "iconfont icon-tokopedia1",
        "placeholder" => "Your link",
    ],
    "roblox1" => [
        "name" => "Roblox",
        "address" => "%s",
        "icon" => "iconfont icon-Roblox1",
        "placeholder" => "Your link",
    ],
    "googlepodcast1" => [
        "name" => "GooglePodcast",
        "address" => "%s",
        "icon" => "iconfont icon-a-GooglePodcast1",
        "placeholder" => "Your link",
    ],
    "lazada1" => [
        "name" => "Lazada",
        "address" => "%s",
        "icon" => "iconfont icon-lazada1",
        "placeholder" => "Your link",
    ],
    "github1" => [
        "name" => "Github",
        "address" => "%s",
        "icon" => "iconfont icon-Github1",
        "placeholder" => "Your link",
    ],
    "redbubble1" => [
        "name" => "Redbubble",
        "address" => "%s",
        "icon" => "iconfont icon-Redbubble1",
        "placeholder" => "Your link",
    ],
    "aliexpress1" => [
        "name" => "AliExpress",
        "address" => "%s",
        "icon" => "iconfont icon-AliExpress1",
        "placeholder" => "Your link",
    ],
    "fiverr1" => [
        "name" => "Fiverr",
        "address" => "%s",
        "icon" => "iconfont icon-Fiverr1",
        "placeholder" => "Your link",
    ],
    "bigo1" => [
        "name" => "Bigo",
        "address" => "%s",
        "icon" => "iconfont icon-bigo1",
        "placeholder" => "Your link",
    ],
    "mercadolibre1" => [
        "name" => "MercadoLibre",
        "address" => "%s",
        "icon" => "iconfont icon-a-MercadoLibre1",
        "placeholder" => "Your link",
    ],
    "tellonym1" => [
        "name" => "Tellonym",
        "address" => "%s",
        "icon" => "iconfont icon-Tellonym1",
        "placeholder" => "Your link",
    ],
    "ivoox1" => [
        "name" => "Ivoox",
        "address" => "%s",
        "icon" => "iconfont icon-ivoox1",
        "placeholder" => "Your link",
    ],
    "coinbase1" => [
        "name" => "Coinbase",
        "address" => "%s",
        "icon" => "iconfont icon-coinbase1",
        "placeholder" => "Your link",
    ],
    "freelancer1" => [
        "name" => "Freelancer",
        "address" => "%s",
        "icon" => "iconfont icon-Freelancer1",
        "placeholder" => "Your link",
    ],
    "beatstars1" => [
        "name" => "Beatstars",
        "address" => "%s",
        "icon" => "iconfont icon-beatstars1",
        "placeholder" => "Your link",
    ],
    "brubank1" => [
        "name" => "Brubank",
        "address" => "%s",
        "icon" => "iconfont icon-brubank1",
        "placeholder" => "Your link",
    ],
    "amino1" => [
        "name" => "Amino",
        "address" => "%s",
        "icon" => "iconfont icon-amino1",
        "placeholder" => "Your link",
    ],
    "nubank1" => [
        "name" => "Nubank",
        "address" => "%s",
        "icon" => "iconfont icon-nubank1",
        "placeholder" => "Your link",
    ],
    "kwai1" => [
        "name" => "Kwai",
        "address" => "%s",
        "icon" => "iconfont icon-kwai1",
        "placeholder" => "Your link",
    ],
    "wordpress1" => [
        "name" => "Wordpress",
        "address" => "%s",
        "icon" => "iconfont icon-wordpress1",
        "placeholder" => "Your link",
    ],
    "upwork" => [
        "name" => "Upwork",
        "address" => "%s",
        "icon" => "iconfont icon-Upwork",
        "placeholder" => "Your link",
    ],
    "calendly" => [
        "name" => "Calendly",
        "address" => "%s",
        "icon" => "iconfont icon-Calendly",
        "placeholder" => "Your link",
    ],
    "freesound" => [
        "name" => "Freesound",
        "address" => "%s",
        "icon" => "iconfont icon-Freesound",
        "placeholder" => "Your link",
    ],
    "dirtyfans" => [
        "name" => "Dirtyfans",
        "address" => "%s",
        "icon" => "iconfont icon-Dirtyfans",
        "placeholder" => "Your link",
    ],
    "ifood" => [
        "name" => "Ifood",
        "address" => "%s",
        "icon" => "iconfont icon-Ifood",
        "placeholder" => "Your link",
    ],
    "slack" => [
        "name" => "Slack",
        "address" => "%s",
        "icon" => "iconfont icon-Slack",
        "placeholder" => "Your link",
    ],
    "deviant_art" => [
        "name" => "Deviant_art",
        "address" => "%s",
        "icon" => "iconfont icon-Deviant_art",
        "placeholder" => "Your link",
    ],
    "beatport" => [
        "name" => "Beatport",
        "address" => "%s",
        "icon" => "iconfont icon-Beatport",
        "placeholder" => "Your link",
    ],
    "skoob" => [
        "name" => "Skoob",
        "address" => "%s",
        "icon" => "iconfont icon-Skoob",
        "placeholder" => "Your link",
    ],
    "kofi" => [
        "name" => "Kofi",
        "address" => "%s",
        "icon" => "iconfont icon-Kofi",
        "placeholder" => "Your link",
    ],
    "resso" => [
        "name" => "Resso",
        "address" => "%s",
        "icon" => "iconfont icon-Resso",
        "placeholder" => "Your link",
    ],
    "picpay" => [
        "name" => "Picpay",
        "address" => "%s",
        "icon" => "iconfont icon-Picpay",
        "placeholder" => "Your link",
    ],
    "strava" => [
        "name" => "Strava",
        "address" => "%s",
        "icon" => "iconfont icon-Strava",
        "placeholder" => "Your link",
    ],
    "hover" => [
        "name" => "Hover",
        "address" => "%s",
        "icon" => "iconfont icon-Hover",
        "placeholder" => "Your link",
    ],
    "poshmark" => [
        "name" => "Poshmark",
        "address" => "%s",
        "icon" => "iconfont icon-Poshmark",
        "placeholder" => "Your link",
    ],
    "bilibili" => [
        "name" => "Bilibili",
        "address" => "%s",
        "icon" => "iconfont icon-Bilibili",
        "placeholder" => "Your link",
    ],
    "blogger" => [
        "name" => "Blogger",
        "address" => "%s",
        "icon" => "iconfont icon-Blogger",
        "placeholder" => "Your link",
    ],
    "depop" => [
        "name" => "Depop",
        "address" => "%s",
        "icon" => "iconfont icon-Depop",
        "placeholder" => "Your link",
    ],
    "trovolive" => [
        "name" => "Trovolive",
        "address" => "%s",
        "icon" => "iconfont icon-a-Trovolive",
        "placeholder" => "Your link",
    ],
    "opensea" => [
        "name" => "Opensea",
        "address" => "%s",
        "icon" => "iconfont icon-Opensea",
        "placeholder" => "Your link",
    ],
    "booksy" => [
        "name" => "Booksy",
        "address" => "%s",
        "icon" => "iconfont icon-Booksy",
        "placeholder" => "Your link",
    ],
    "cash" => [
        "name" => "Cash",
        "address" => "%s",
        "icon" => "iconfont iconfont icon-Cash",
        "placeholder" => "Your link",
    ],
    "disqus" => [
        "name" => "Disqus",
        "address" => "%s",
        "icon" => "iconfont icon-Disqus",
        "placeholder" => "Your link",
    ],
];
