<?php

return [
    'links' => [
        'name' => 'Button Links',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-link',
        'ori-icon-svg' => 'interface-essential---broken-link-unlink copy',
        'color' => '#884A39',
        'category' => 'essentials',
        'completed' => true,
    ],
    'text' => [
        'name' => 'Text',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-text',
        'ori-icon-svg' => 'interface-essential---text-edit-pen-t',
        'color' => '#EA1179',
        'category' => 'essentials',
        'completed' => true,
    ],
    'article' => [
        'name' => 'Article',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-text',
        'ori-icon-svg' => 'Files---documents-file-text copy',
        'color' => '#E9B824',
        'category' => 'essentials',
        'completed' => true,
    ],
    'image' => [
        'name' => 'Image Grid',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-graphic-style',
        'ori-icon-svg' => 'interface-essential---image-picture-circle copy',
        'color' => '#916DB3',
        'category' => 'essentials',
        'completed' => true,
    ],
    'subscribe' => [
        'name' => 'Subscribe',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-images',
        'ori-icon-svg' => 'emails---Mail, Email, Letter.8',
        'color' => '#A1CCD1',
        'category' => 'essentials',
        'completed' => true,
    ],
    'location' => [
        'name' => 'Location Map',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-map-marker',
        'ori-icon-svg' => 'Maps, Navigation---Pin, Location, Map.1',
        'color' => '#98EECC',
        'category' => 'essentials',
        'completed' => true,
    ],
    'slider' => [
        'name' => 'Image Slider',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-images',
        'ori-icon-svg' => 'interface-essential---slides-windows.2',
        'color' => '#E4A5FF',
        'category' => 'essentials',
        'completed' => true,
    ],
    'faq' => [
        'name' => 'Faq',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-comments-question',
        'ori-icon-svg' => 'Support, Help, Question---Question, Loading',
        'color' => '#C23373',
        'category' => 'essentials',
        'completed' => true,
    ],
    'features' => [
        'name' => 'Features',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-list',
        'ori-icon-svg' => 'Type, Paragraph, Character---list-paragraph-dots-circle_1',
        'color' => '#FFBFBF',
        'category' => 'essentials',
        'completed' => true,
    ],
    'socialimage' => [
        'name' => 'Social Images',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-desktop-wallpaper',
        'ori-icon-svg' => 'interface-essential---images-pictures-copy',
        'color' => '#EADBC8',
        'category' => 'essentials'
    ],


    
    'embed' => [
        'name' => 'Embed',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-play-alt',
        'ori-icon-svg' => 'Video, Movies---browser-video-player',
        'color' => '#EDB7ED',
        'category' => 'media',
        'completed' => true,
    ],
    'video' => [
        'name' => 'Video',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-play-alt',
        'ori-icon-svg' => 'Video, Movies---video-player',
        'color' => '#0C134F',
        'category' => 'media',
        'completed' => true,
    ],
    'youtube' => [
        'name' => 'Youtube',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-play-alt',
        'ori-icon-svg' => 'Social Media---Youtube, Square',
        'color' => '#FF0000',
        'category' => 'media',
        'completed' => true,
    ],
    // 'twitter' => [
    //     'name' => 'X (Formerly Twitter)',
    //     'desc' => 'Links for everything',
    //     'icon' => 'fi fi-rr-play-alt',
    //     'ori-icon-svg' => 'custom---x-social-icon',
    //     'color' => '#000000',
    //     'category' => 'media',
    //     'completed' => true,
    // ],
    'tiktok' => [
        'name' => 'Tiktok',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-play-alt',
        'ori-icon-svg' => 'custom---tiktok',
        'color' => '#000000',
        'category' => 'media',
        'completed' => true,
    ],
    'twitch' => [
        'name' => 'Twitch',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-play-alt',
        'ori-icon-svg' => 'Social Media---Twitch, TV',
        'color' => '#6441a5',
        'category' => 'media',
        'completed' => true,
    ],


    
    'timer' => [
        'name' => 'Timer',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-play-alt',
        'ori-icon-svg' => 'Sport, Fitness---timer',
        'color' => '#4C4B16',
        'category' => 'growth',
        'completed' => true,
    ],
    // 'contact' => [
    //     'name' => 'Contact Me',
    //     'desc' => 'Links for everything',
    //     'icon' => 'fi fi-rr-play-alt',
    //     'ori-icon-svg' => 'Files---Documents, File, Contacts',
    //     'color' => '#FEFFAC',
    //     'category' => 'growth',
    //     'completed' => true,
    // ],
    'sendwhatsapp' => [
        'name' => 'Send To Whatsapp',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-play-alt',
        'ori-icon-svg' => 'Social Media---Whatsup',
        'color' => '#075e54',
        'category' => 'growth',
        'completed' => true,
    ],
    'skillbar' => [
        'name' => 'Skill Bar',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-play-alt',
        'ori-icon-svg' => 'Business, Products---Business, Chart.18',
        'color' => '#E7B10A',
        'category' => 'growth',
        'completed' => true,
    ],

    
    'tipjar' => [
        'name' => 'Tipjar',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-play-alt',
        'ori-icon-svg' => 'Payments Finance---Piggy bank, Coin.1',
        'color' => '#AAC8A7',
        'category' => 'monetize',
        'completed' => true,
    ],
    'shop' => [
        'name' => 'Shop',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-store-alt',
        'ori-icon-svg' => 'shopping-ecommerce---mobile-app-store',
        'color' => '#FFE569',
        'category' => 'monetize',
        'completed' => true,
    ],
    'coupon' => [
        'name' => 'Coupon',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-play-alt',
        'ori-icon-svg' => 'shopping-ecommerce---Coupon, Discount.1',
        'color' => '#EA906C',
        'category' => 'monetize',
        'completed' => true,
    ],
    'course' => [
        'name' => 'Course',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-book-open-cover',
        'ori-icon-svg' => 'interface-essential---book.1',
        'color' => '#D4E2D4',
        'category' => 'monetize',
        'completed' => true,
    ],
    'booking' => [
        'name' => 'Booking',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-calendar',
        'ori-icon-svg' => 'interface-essential---calendar-schedule-31.2',
        'color' => '#EDE4FF',
        'onlyOnce' => true,
        'category' => 'monetize',
        'completed' => true,
    ],
    'bankcrypto' => [
        'name' => 'Bank and Crypto Wallet',
        'desc' => 'Links for everything',
        'icon' => 'fi fi-rr-play-alt',
        'ori-icon-svg' => 'Crypto Currency---Crypto, Currency, Bitcoin, Ethereum.5',
        'color' => '#CECE5A',
        'category' => 'monetize',
        'completed' => true,
    ],
];
