<?php

namespace App\Yena;

class Country {

	public static function icon($country){
		$country = strtolower($country);


		return gs('assets/image/countries', "$country.svg");
	}

	public static function google_trans_lang(){
		

		$array = [
			["language" => "Afrikaans", "code" => "af"],
			["language" => "Albanian", "code" => "sq", "country" => "al"],
			["language" => "Amharic", "code" => "am"],
			["language" => "Arabic", "code" => "ar"],
			["language" => "Armenian", "code" => "hy", "country" => "am"],
			["language" => "Azerbaijani", "code" => "az"],
			["language" => "Basque", "code" => "eu"],
			["language" => "Belarusian", "code" => "be"],
			["language" => "Bengali", "code" => "bn"],
			["language" => "Bosnian", "code" => "bs"],
			["language" => "Bulgarian", "code" => "bg"],
			["language" => "Catalan", "code" => "ca"],
			["language" => "Cebuano", "code" => "ceb", "country" => "ph"],
			["language" => "Chinese (Simplified)", "code" => "zh-CN", "country" => "cn"],
			["language" => "Chinese (Traditional)", "code" => "zh-TW", "country" => "cn"],
			["language" => "Corsican", "code" => "co"],
			["language" => "Croatian", "code" => "hr"],
			["language" => "Czech", "code" => "cs", "country" => "cz"],
			["language" => "Danish", "code" => "da", "country" => "dk"],
			["language" => "Dutch", "code" => "nl"],
			["language" => "English", "code" => "en", "country" => "us"],
			//["language" => "Esperanto", "code" => "eo"],
			["language" => "Estonian", "code" => "et"],
			["language" => "Finnish", "code" => "fi"],
			["language" => "French", "code" => "fr"],
			["language" => "Frisian", "code" => "fy", "country" => "nl"],
			["language" => "Galician", "code" => "gl"],
			["language" => "Georgian", "code" => "ka", "country" => "ge"],
			["language" => "German", "code" => "de"],
			["language" => "Greek", "code" => "el", 'country' => 'GR'],
			["language" => "Gujarati", "code" => "gu"],
			["language" => "Haitian Creole", "code" => "ht"],
			["language" => "Hausa", "code" => "ha", 'country' => 'NG'],
			["language" => "Hawaiian", "code" => "haw", 'country' => 'us'],
			["language" => "Hebrew", "code" => "iw", 'country' => 'il'],
			["language" => "Hindi", "code" => "hi", 'country' => 'IN'],
			//["language" => "Hmong", "code" => "hmn"],
			["language" => "Hungarian", "code" => "hu"],
			["language" => "Icelandic", "code" => "is"],
			["language" => "Igbo", "code" => "ig", 'country' => 'NG'],
			["language" => "Indonesian", "code" => "id"],
			["language" => "Irish", "code" => "ga"],
			["language" => "Italian", "code" => "it"],
			["language" => "Japanese", "code" => "ja", "country" => "jp"],
			["language" => "Javanese", "code" => "jw", 'country' => 'ID'],
			["language" => "Kannada", "code" => "kn"],
			["language" => "Kazakh", "code" => "kk", 'country' => 'KZ'],
			["language" => "Khmer", "code" => "km"],
			["language" => "Korean", "code" => "ko", 'country' => 'KP'],
			["language" => "Kurdish", "code" => "ku", 'country' => 'TR'],
			["language" => "Kyrgyz", "code" => "ky"],
			["language" => "Lao", "code" => "lo", 'country' => 'la'],
			["language" => "Latin", "code" => "la"],
			["language" => "Latvian", "code" => "lv"],
			["language" => "Lithuanian", "code" => "lt"],
			["language" => "Luxembourgish", "code" => "lb"],
			["language" => "Macedonian", "code" => "mk"],
			["language" => "Malagasy", "code" => "mg"],
			["language" => "Malay", "code" => "ms"],
			["language" => "Malayalam", "code" => "ml"],
			["language" => "Maltese", "code" => "mt"],
			["language" => "Maori", "code" => "mi", "country" => "nz"],
			["language" => "Marathi", "code" => "mr"],
			["language" => "Mongolian", "code" => "mn"],
			["language" => "Myanmar (Burmese)", "code" => "my"],
			["language" => "Nepali", "code" => "ne"],
			["language" => "Norwegian", "code" => "no"],
			["language" => "Nyanja (Chichewa)", "code" => "ny", "country" => "mw"],
			["language" => "Pashto", "code" => "ps"],
			["language" => "Persian", "code" => "fa", "country" => "ir"],
			["language" => "Polish", "code" => "pl"],
			["language" => "Portuguese", "code" => "pt"],
			["language" => "Punjabi", "code" => "pa"],
			["language" => "Romanian", "code" => "ro"],
			["language" => "Russian", "code" => "ru"],
			["language" => "Samoan", "code" => "sm"],
			["language" => "Scots Gaelic", "code" => "gd"],
			["language" => "Serbian", "code" => "sr"],
			["language" => "Sesotho", "code" => "st"],
			["language" => "Shona", "code" => "sn"],
			["language" => "Sindhi", "code" => "sd"],
			["language" => "Sinhala (Sinhalese)", "code" => "si"],
			["language" => "Slovak", "code" => "sk"],
			["language" => "Slovenian", "code" => "sl"],
			["language" => "Somali", "code" => "so"],
			["language" => "Spanish", "code" => "es"],
			["language" => "Sundanese", "code" => "su", "country" => "in"],
			["language" => "Swedish", "code" => "sv"],
			["language" => "Tagalog (Filipino)", "code" => "tl"],
			["language" => "Tajik", "code" => "tg"],
			["language" => "Tamil", "code" => "ta", "country" => "in"],
			["language" => "Telugu", "code" => "te", "country" => "in"],
			["language" => "Thai", "code" => "th"],
			["language" => "Turkish", "code" => "tr"],
			["language" => "Ukrainian", "code" => "uk", "country" => "ua"],
			["language" => "Urdu", "code" => "ur", "country" => "pk"],
			["language" => "Uzbek", "code" => "uz"],
			["language" => "Vietnamese", "code" => "vi"],
			["language" => "Welsh", "code" => "cy"],
			["language" => "Xhosa", "code" => "xh", "country" => "za"],
			//["language" => "Yiddish", "code" => "yi", "country" => "al"],
			["language" => "Yoruba", "code" => "yo", "country" => "ng"],
			["language" => "Zulu", "code" => "zu", "country" => "za"],
		];

		return $array;
	}

	public static function list(){
	    $country_list = [
	        'AF' => 'Afghanistan',
	        'AX' => 'Aland Islands',
	        'AL' => 'Albania',
	        'DZ' => 'Algeria',
	        'AS' => 'American Samoa',
	        'AD' => 'Andorra',
	        'AO' => 'Angola',
	        'AI' => 'Anguilla',
	        'AQ' => 'Antarctica',
	        'AG' => 'Antigua and Barbuda',
	        'AR' => 'Argentina',
	        'AM' => 'Armenia',
	        'AW' => 'Aruba',
	        'AU' => 'Australia',
	        'AT' => 'Austria',
	        'AZ' => 'Azerbaijan',
	        'BS' => 'Bahamas the',
	        'BH' => 'Bahrain',
	        'BD' => 'Bangladesh',
	        'BB' => 'Barbados',
	        'BY' => 'Belarus',
	        'BE' => 'Belgium',
	        'BZ' => 'Belize',
	        'BJ' => 'Benin',
	        'BM' => 'Bermuda',
	        'BT' => 'Bhutan',
	        'BO' => 'Bolivia',
	        'BA' => 'Bosnia and Herzegovina',
	        'BW' => 'Botswana',
	        'BV' => 'Bouvet Island (Bouvetoya)',
	        'BR' => 'Brazil',
	        'IO' => 'British Indian Ocean Territory (Chagos Archipelago)',
	        'VG' => 'British Virgin Islands',
	        'BN' => 'Brunei Darussalam',
	        'BG' => 'Bulgaria',
	        'BF' => 'Burkina Faso',
	        'BI' => 'Burundi',
	        'KH' => 'Cambodia',
	        'CM' => 'Cameroon',
	        'CA' => 'Canada',
	        'CV' => 'Cape Verde',
	        'KY' => 'Cayman Islands',
	        'CF' => 'Central African Republic',
	        'TD' => 'Chad',
	        'CL' => 'Chile',
	        'CN' => 'China',
	        'CX' => 'Christmas Island',
	        'CC' => 'Cocos (Keeling) Islands',
	        'CO' => 'Colombia',
	        'KM' => 'Comoros the',
	        'CD' => 'Congo',
	        'CG' => 'Congo the',
	        'CK' => 'Cook Islands',
	        'CR' => 'Costa Rica',
	        'CI' => 'Cote d\'Ivoire',
	        'HR' => 'Croatia',
	        'CU' => 'Cuba',
	        'CY' => 'Cyprus',
	        'CZ' => 'Czech Republic',
	        'DK' => 'Denmark',
	        'DJ' => 'Djibouti',
	        'DM' => 'Dominica',
	        'DO' => 'Dominican Republic',
	        'EC' => 'Ecuador',
	        'EG' => 'Egypt',
	        'SV' => 'El Salvador',
	        'GQ' => 'Equatorial Guinea',
	        'ER' => 'Eritrea',
	        'EE' => 'Estonia',
	        'ET' => 'Ethiopia',
	        'FO' => 'Faroe Islands',
	        'FK' => 'Falkland Islands (Malvinas)',
	        'FJ' => 'Fiji the Fiji Islands',
	        'FI' => 'Finland',
	        'FR' => 'France, French Republic',
	        'GF' => 'French Guiana',
	        'PF' => 'French Polynesia',
	        'TF' => 'French Southern Territories',
	        'GA' => 'Gabon',
	        'GM' => 'Gambia the',
	        'GE' => 'Georgia',
	        'DE' => 'Germany',
	        'GH' => 'Ghana',
	        'GI' => 'Gibraltar',
	        'GR' => 'Greece',
	        'GL' => 'Greenland',
	        'GD' => 'Grenada',
	        'GP' => 'Guadeloupe',
	        'GU' => 'Guam',
	        'GT' => 'Guatemala',
	        'GG' => 'Guernsey',
	        'GN' => 'Guinea',
	        'GW' => 'Guinea-Bissau',
	        'GY' => 'Guyana',
	        'HT' => 'Haiti',
	        'HM' => 'Heard Island and McDonald Islands',
	        'VA' => 'Holy See (Vatican City State)',
	        'HN' => 'Honduras',
	        'HK' => 'Hong Kong',
	        'HU' => 'Hungary',
	        'IS' => 'Iceland',
	        'IN' => 'India',
	        'ID' => 'Indonesia',
	        'IR' => 'Iran',
	        'IQ' => 'Iraq',
	        'IE' => 'Ireland',
	        'IM' => 'Isle of Man',
	        'IL' => 'Israel',
	        'IT' => 'Italy',
	        'JM' => 'Jamaica',
	        'JP' => 'Japan',
	        'JE' => 'Jersey',
	        'JO' => 'Jordan',
	        'KZ' => 'Kazakhstan',
	        'KE' => 'Kenya',
	        'KI' => 'Kiribati',
	        'KP' => 'Korea',
	        'KR' => 'Korea',
	        'KW' => 'Kuwait',
	        'KG' => 'Kyrgyz Republic',
	        'LA' => 'Lao',
	        'LV' => 'Latvia',
	        'LB' => 'Lebanon',
	        'LS' => 'Lesotho',
	        'LR' => 'Liberia',
	        'LY' => 'Libyan Arab Jamahiriya',
	        'LI' => 'Liechtenstein',
	        'LT' => 'Lithuania',
	        'LU' => 'Luxembourg',
	        'MO' => 'Macao',
	        'MK' => 'Macedonia',
	        'MG' => 'Madagascar',
	        'MW' => 'Malawi',
	        'MY' => 'Malaysia',
	        'MV' => 'Maldives',
	        'ML' => 'Mali',
	        'MT' => 'Malta',
	        'MH' => 'Marshall Islands',
	        'MQ' => 'Martinique',
	        'MR' => 'Mauritania',
	        'MU' => 'Mauritius',
	        'YT' => 'Mayotte',
	        'MX' => 'Mexico',
	        'FM' => 'Micronesia',
	        'MD' => 'Moldova',
	        'MC' => 'Monaco',
	        'MN' => 'Mongolia',
	        'ME' => 'Montenegro',
	        'MS' => 'Montserrat',
	        'MA' => 'Morocco',
	        'MZ' => 'Mozambique',
	        'MM' => 'Myanmar',
	        'NA' => 'Namibia',
	        'NR' => 'Nauru',
	        'NP' => 'Nepal',
	        'AN' => 'Netherlands Antilles',
	        'NL' => 'Netherlands the',
	        'NC' => 'New Caledonia',
	        'NZ' => 'New Zealand',
	        'NI' => 'Nicaragua',
	        'NE' => 'Niger',
	        'NG' => 'Nigeria',
	        'NU' => 'Niue',
	        'NF' => 'Norfolk Island',
	        'MP' => 'Northern Mariana Islands',
	        'NO' => 'Norway',
	        'OM' => 'Oman',
	        'PK' => 'Pakistan',
	        'PW' => 'Palau',
	        'PS' => 'Palestinian Territory',
	        'PA' => 'Panama',
	        'PG' => 'Papua New Guinea',
	        'PY' => 'Paraguay',
	        'PE' => 'Peru',
	        'PH' => 'Philippines',
	        'PN' => 'Pitcairn Islands',
	        'PL' => 'Poland',
	        'PT' => 'Portugal, Portuguese Republic',
	        'PR' => 'Puerto Rico',
	        'QA' => 'Qatar',
	        'RE' => 'Reunion',
	        'RO' => 'Romania',
	        'RU' => 'Russian Federation',
	        'RW' => 'Rwanda',
	        'BL' => 'Saint Barthelemy',
	        'SH' => 'Saint Helena',
	        'KN' => 'Saint Kitts and Nevis',
	        'LC' => 'Saint Lucia',
	        'MF' => 'Saint Martin',
	        'PM' => 'Saint Pierre and Miquelon',
	        'VC' => 'Saint Vincent and the Grenadines',
	        'WS' => 'Samoa',
	        'SM' => 'San Marino',
	        'ST' => 'Sao Tome and Principe',
	        'SA' => 'Saudi Arabia',
	        'SN' => 'Senegal',
	        'RS' => 'Serbia',
	        'SC' => 'Seychelles',
	        'SL' => 'Sierra Leone',
	        'SG' => 'Singapore',
	        'SK' => 'Slovakia (Slovak Republic)',
	        'SI' => 'Slovenia',
	        'SB' => 'Solomon Islands',
	        'SO' => 'Somalia, Somali Republic',
	        'ZA' => 'South Africa',
	        'GS' => 'South Georgia and the South Sandwich Islands',
	        'ES' => 'Spain',
	        'LK' => 'Sri Lanka',
	        'SD' => 'Sudan',
	        'SR' => 'Suriname',
	        'SJ' => 'Svalbard & Jan Mayen Islands',
	        'SZ' => 'Swaziland',
	        'SE' => 'Sweden',
	        'CH' => 'Switzerland, Swiss Confederation',
	        'SY' => 'Syrian Arab Republic',
	        'TW' => 'Taiwan',
	        'TJ' => 'Tajikistan',
	        'TZ' => 'Tanzania',
	        'TH' => 'Thailand',
	        'TL' => 'Timor-Leste',
	        'TG' => 'Togo',
	        'TK' => 'Tokelau',
	        'TO' => 'Tonga',
	        'TT' => 'Trinidad and Tobago',
	        'TN' => 'Tunisia',
	        'TR' => 'Turkey',
	        'TM' => 'Turkmenistan',
	        'TC' => 'Turks and Caicos Islands',
	        'TV' => 'Tuvalu',
	        'UG' => 'Uganda',
	        'UA' => 'Ukraine',
	        'AE' => 'United Arab Emirates',
	        'GB' => 'United Kingdom',
	        'US' => 'United States of America',
	        'UM' => 'United States Minor Outlying Islands',
	        'VI' => 'United States Virgin Islands',
	        'UY' => 'Uruguay, Eastern Republic of',
	        'UZ' => 'Uzbekistan',
	        'VU' => 'Vanuatu',
	        'VE' => 'Venezuela',
	        'VN' => 'Vietnam',
	        'WF' => 'Wallis and Futuna',
	        'EH' => 'Western Sahara',
	        'YE' => 'Yemen',
	        'ZM' => 'Zambia',
	        'ZW' => 'Zimbabwe'
	    ];

	    return $country_list;
	}
	public static function country_code($code) {
	    $code = strtoupper($code);

	    $country_list = self::list();

	    if (array_key_exists($code, $country_list)) {
	    	return ao($country_list, $code);
	    }else{
	    	return $code;
	    }
	}
}
