<?php

return [
    'sections' => [
        [
            "section" => "banner",
            "image" => "assets/image/dragdrop/5.png",
            "content" => [
                "title" => "Create beautiful \n websites with AI",
                "subtitle" => "Design stunning websites effortlessly with the free Mewayz AI. Our intuitive AI-powered builder allows for seamless mobile editing and automatic saving, making website creation a breeze.",
            ],
            "settings" => [
                "banner_style" => "3",
                "shape_avatar" => 100,
                "enable_image" => true,
                "actiontype" => "button",
                "align" => "left",
                "height" => "500",
                "width" => "75",
                "title" => "m",
                "image_type" => "fit",
                "enable_action" => true,
                "button_one_text" => "Learn More",
                "button_two_text" => "Create Site Free",
                "color" => "default",
            ],
            "section_settings" => [
                "height" => "fit",
                "width" => "fill",
                "spacing" => "xl",
                "align" => "center",
                "color" => "transparent",
            ],
            "form" => ["email" => "Email", "button_name" => "Signup"],
            "items" => [],
        ],
        [
            "section" => "review",
            "content" => ["title" => ""],
            "settings" => [
                "style" => "2",
                "align" => "center",
                "desktop_grid" => 3,
                "mobile_grid" => 1,
                "text" => "s",
                "background" => true,
                "rating" => true,
                "avatar" => false,
                "type" => "stars",
                "shape" => "square",
                "split_title" => false,
                "border" => false,
                "display" => "grid",
            ],
            "section_settings" => [
                "height" => "fit",
                "width" => "fill",
                "spacing" => "l",
                "align" => "center",
            ],
            "form" => [],
            "items" => [
                [
                    "content" => [
                        "title" => "Angela Parker",
                        "bio" => "Marketing Strategist",
                        "text" =>
                            "I was able to customize every detail to my liking and the end result professional and polished.",
                        "rating" => "5",
                        "image" => null,
                    ],
                    "settings" => ["animation" => "-"],
                ],
                [
                    "content" => [
                        "title" => "Lauren Thompson",
                        "bio" => "Executive Development Coordinator",
                        "text" => "It's incredibly easy to use and I was able to create a professional-looking website in no time.",
                        "rating" => "5",
                        "image" => null,
                    ],
                    "settings" => ["animation" => "-"],
                ],
                [
                    "content" => [
                        "title" => "Dylan Cooper",
                        "bio" => "Product Development Coordinator",
                        "text" =>
                            "I was able to design a professional-looking site in no time thanks Mewayz's user-friendly design tools. ",
                        "rating" => "5",
                        "image" => null,
                    ],
                    "settings" => ["animation" => "-"],
                ],
            ],
        ],
        [
            "section" => "banner",
            "image" => "assets/image/dragdrop/12.png",
            "content" => [
                "title" => "AI-powered \n website builder ✨",
                "subtitle" =>
                    "Mewayz AI automates website design based on your business description. Create websites without coding. Manage multiple sites with custom domains, suitable for freelancers and small businesses.",
            ],
            "settings" => [
                "banner_style" => "3",
                "shape_avatar" => 100,
                "enable_image" => true,
                "actiontype" => "button",
                "align" => "left",
                "height" => "400",
                "width" => "75",
                "title" => "s",
                "image_type" => "fit",
                "enable_action" => false,
                "button_one_text" => "Button 1",
                "button_two_text" => "Button 2",
                "color" => "default",
            ],
            "section_settings" => [
                "height" => "fit",
                "width" => "fill",
                "spacing" => "l",
                "align" => "center",
            ],
            "form" => ["email" => "Email", "button_name" => "Signup"],
            "items" => [],
        ],
        [
            "section" => "banner",
            "image" => "assets/image/dragdrop/3.png",
            "content" => [
                "title" => "Easy customization \n on any browser 😍",
                "subtitle" =>
                    "Zeph website builder is user-friendly and mobile-friendly, allowing you to easily update your website while on the go. With a simple click, you can personalize your entire site with cohesive fonts, colors, and shapes that align with your brand\'s aesthetic.",
            ],
            "settings" => [
                "banner_style" => "4",
                "shape_avatar" => 100,
                "enable_image" => true,
                "actiontype" => "button",
                "align" => "left",
                "height" => "450",
                "width" => "75",
                "title" => "s",
                "image_type" => "fit",
                "enable_action" => false,
                "button_one_text" => "Button 1",
                "button_two_text" => "Button 2",
                "color" => "default",
            ],
            "section_settings" => [
                "height" => "fit",
                "width" => "fill",
                "spacing" => "l",
                "align" => "center",
            ],
            "form" => ["email" => "Email", "button_name" => "Signup"],
            "items" => [],
        ],
        [
            "section" => "banner",
            "image" => "assets/image/dragdrop/10.png",
            "content" => [
                "title" => "Enjoy access to \n essential tools ⚡️",
                "subtitle" => "Zeph provides SSL for website security, CDN for faster loading, AWS & Google Cloud hosting for reliability. Forms, CRM for email capture, privacy-focused analytics, SEO, and social sharing for online visibility. Easy website transfer or export if hosting elsewhere.",
            ],
            "settings" => [
                "banner_style" => "3",
                "shape_avatar" => 100,
                "enable_image" => true,
                "actiontype" => "button",
                "align" => "left",
                "height" => "450",
                "width" => "75",
                "title" => "s",
                "image_type" => "fit",
                "enable_action" => false,
                "button_one_text" => "Button 1",
                "button_two_text" => "Button 2",
                "color" => "default",
            ],
            "section_settings" => [
                "height" => "fit",
                "width" => "fill",
                "spacing" => "l",
                "align" => "center",
            ],
            "form" => ["email" => "Email", "button_name" => "Signup"],
            "items" => [],
        ],
        [
            "section" => "pricing",
            "content" => [
                "title" => "Pricing",
                "subtitle" =>
                    "Simple per-user pricing for freelancers and agencies",
            ],
            "settings" => [
                "style" => "1",
                "align" => "left",
                "layout" => "left",
                "display" => "grid",
                "desktop_grid" => 3,
                "mobile_grid" => 1,
                "text" => "m",
                "background" => true,
                "icon" => true,
                "type" => "plans",
                "shape" => "square",
                "desktop_height" => "50",
                "currency" => "USD",
            ],
            "section_settings" => [
                "height" => "fit",
                "width" => "fill",
                "spacing" => "l",
                "align" => "center",
            ],
            "form" => [],
            "items" => [
                [
                    "content" => [
                        "title" => "Free",
                        "button" => "Get started",
                        "single_price" => "0",
                        "month_price" => "0",
                        "year_price" => "0",
                        "features" => [
                            ["name" => "Ai"],
                            ["name" => "SEO support"],
                            ["name" => "100 contacts"],
                            ["name" => "3 pages"],
                            ["name" => "1 site"],
                            ["name" => "100mb storage"],
                            ["name" => "Zeph Domain"],
                        ],
                        "popular_price" => false,
                        "text" => "",
                    ],
                    "settings" => ["animation" => "-"],
                ],
                [
                    "content" => [
                        "image" => null,
                        "title" => "Basic",
                        "button" => "Get started",
                        "single_price" => "0",
                        "month_price" => "15",
                        "year_price" => "30",
                        "features" => [
                            ["name" => "Ai"],
                            ["name" => "Ai images"],
                            ["name" => "Custom Domain"],
                            ["name" => "Custom Branding"],
                            ["name" => "10 pages"],
                            ["name" => "1000 contacts"],
                            ["name" => "10 sites"],
                            ["name" => "5gb storage"],
                            ["name" => "SEO support"],
                        ],
                    ],
                    "settings" => null,
                ],
                [
                    "content" => [
                        "title" => "Business",
                        "button" => "Get started",
                        "single_price" => "0",
                        "month_price" => "35",
                        "year_price" => "50",
                        "features" => [
                            ["name" => "Ai"],
                            ["name" => "Ai images"],
                            ["name" => "Custom Branding"],
                            ["name" => "Pixel Codes"],
                            ["name" => "Custom Domain"],
                            ["name" => "Unlimited uploads"],
                            ["name" => "Unlimited pages"],
                            ["name" => "Unlimited contacts"],
                            ["name" => "Unlimited site"],
                            ["name" => "Export to HTML"],
                            ["name" => "Insight"],
                        ],
                        "popular_price" => true,
                        "button_link" => "/register",
                    ],
                    "settings" => ["animation" => "-"],
                ],
            ],
        ],
        [
            "section" => "accordion",
            "content" => ["title" => "Popular questions", "subtitle" => ""],
            "settings" => ["banner_style" => 1],
            "section_settings" => [
                "height" => "fit",
                "width" => "fill",
                "spacing" => "l",
                "align" => "center",
            ],
            "form" => [],
            "items" => [
                [
                    "content" => [
                        "title" => "Who are we?",
                        "text" => "Zeph makes website creation a breeze. Simply inform Zeph about your business and let it do the rest! Effortlessly craft a beautiful website without the need for coding or design expertise.",
                    ],
                    "settings" => ["animation" => "-"],
                ],
                [
                    "content" => [
                        "title" => "What can we do?",
                        "text" =>
                            "Creating a website is a breeze with Zeph. Simply provide us with details about your business, and our AI will take care of the rest by incorporating content, design, images, forms, and SEO. You have the flexibility to edit and launch your website from your mobile device or desktop browser.",
                    ],
                    "settings" => null,
                ],
                [
                    "content" => [
                        "title" => "Do we include hosting?",
                        "text" =>
                            "Oh yes, Zeph has everything you need for website hosting. From SSL for secure connections to CDN for lightning-fast website loading, and AWS hosting for top-notch performance. Your website will be completely secure, super fast, and readily available for your visitors.",
                    ],
                    "settings" => null,
                ],
                [
                    "content" => [
                        "title" => "How much do we charge?",
                        "text" =>
                            "We offer two payment plans for you: Free and Pro. Our plans include a personalized domain, web hosting, and CRM. However, the key difference is that with Pro, you have the ability to export your website and incorporate custom coding.",
                    ],
                    "settings" => null,
                ],
            ],
        ],
        [
            "section" => "banner",
            "image" => "assets/image/dragdrop/17.png",
            "content" => [
                "title" => "The easiest way to \n create a website",
                "subtitle" => "No coding or design skills needed",
            ],
            "settings" => [
                "banner_style" => "2",
                "shape_avatar" => 100,
                "enable_image" => true,
                "actiontype" => "button",
                "align" => "center",
                "height" => "320",
                "width" => "71",
                "title" => "s",
                "image_type" => "fit",
                "enable_action" => false,
                "button_one_text" => "Button 1",
                "button_two_text" => "Button 2",
            ],
            "section_settings" => [
                "height" => "fit",
                "width" => "fill",
                "spacing" => "l",
                "align" => "center",
            ],
            "form" => ["email" => "Email", "button_name" => "Signup"],
            "items" => [],
        ],
    ]    
];